# Generated by Django 5.0.3 on 2024-05-01 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_alter_appuser_is_superuser'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appuser',
            table='user',
        ),
    ]
