# Generated by Django 5.0.3 on 2024-05-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0013_alter_chatbotdata_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='mark',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
