# Generated by Django 5.0.3 on 2024-05-28 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0018_alter_chatbotdata_flow_alter_flow_scenery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='scenery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenery', to='myapi.scenery'),
        ),
    ]
