# Generated by Django 5.0.3 on 2024-05-01 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_alter_appuser_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appuser',
            table='appuser',
        ),
    ]
