# Generated by Django 5.0.3 on 2024-05-01 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_alter_appuser_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='flow',
            table='flow',
        ),
        migrations.AlterModelTable(
            name='step',
            table='step',
        ),
    ]
