# Generated by Django 5.0.3 on 2024-05-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_alter_flow_table_alter_step_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
