# Generated by Django 5.0.3 on 2024-05-05 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0009_scenery_step_scenery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='scenery',
        ),
        migrations.AddField(
            model_name='flow',
            name='scenery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scenery', to='myapi.scenery'),
            preserve_default=False,
        ),
    ]
