# Generated by Django 5.0.3 on 2024-05-23 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0014_alter_mark_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumMessage',
            fields=[
                ('mensaje_id', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_foro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'forum_message',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
