# Generated by Django 5.0.3 on 2024-05-23 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0015_forummessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forummessage',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='forummessage',
            old_name='contenido',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='forummessage',
            old_name='fecha_creacion',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='forummessage',
            old_name='mensaje_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='forummessage',
            old_name='usuario',
            new_name='user',
        ),
    ]
