# Generated by Django 5.0.3 on 2024-05-27 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0016_alter_forummessage_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forummessage',
            old_name='content',
            new_name='message',
        ),
    ]
