# Generated by Django 5.0.3 on 2024-06-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0025_flow_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='description',
            field=models.CharField(default='Bienvenido al flujo. Recuerda empezar saludando !', max_length=500),
        ),
    ]
